

CREATE OR REPLACE FUNCTION inserir_curso(P_TL_CURSO VARCHAR(50), P_DS_CURSO VARCHAR(1000), P_OBJ_CURSO VARCHAR(1000), P_TOPICOS_CURSO VARCHAR(1000), P_PRE_REQ_CURSO VARCHAR(1000), P_DURACAO_CURSO VARCHAR(1000))
RETURNS INTEGER AS
$BODY$
DECLARE
	ID_NOVO INTEGER := 0;
BEGIN
	INSERT INTO CURSO (TL_CURSO, DS_CURSO, OBJ_CURSO, TOPICOS_CURSO, PRE_REQ_CURSO, DURACAO_CURSO, DT_CADASTRO)
        VALUES (P_TL_CURSO, P_DS_CURSO, P_OBJ_CURSO, P_TOPICOS_CURSO, P_PRE_REQ_CURSO, P_DURACAO_CURSO, CURRENT_TIMESTAMP)
        RETURNING ID_CURSO INTO ID_NOVO;
	RETURN ID_NOVO;
END;
$BODY$
LANGUAGE plpgsql VOLATILE;

---------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION inserir_usuario(P_ID_TIPO_USUARIO INTEGER, P_NM_USUARIO VARCHAR(100), P_EMAIL_USUARIO VARCHAR(50), P_SENHA_USUARIO CHAR(6), P_LINK_IMAGEM_USUARIO VARCHAR(500))
RETURNS INTEGER AS
$BODY$
DECLARE
	ID_NOVO INTEGER := 0;
BEGIN
	INSERT INTO USUARIO (ID_TIPO_USUARIO, NM_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, LINK_IMAGEM_USUARIO, DT_CADASTRO)
        VALUES (P_ID_TIPO_USUARIO, P_NM_USUARIO, P_EMAIL_USUARIO, P_SENHA_USUARIO, P_LINK_IMAGEM_USUARIO, CURRENT_TIMESTAMP);
        RETURNING ID_USUARIO INTO ID_NOVO;
	RETURN ID_NOVO;
END;
$BODY$
LANGUAGE plpgsql VOLATILE;

---------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION inserir_aula(P_TL_AULA VARCHAR(50), P_DS_AULA VARCHAR(1000), P_ID_CURSO INTEGER, P_LINK_AULA VARCHAR(500))
RETURNS INTEGER AS
$BODY$
DECLARE
	ID_NOVO INTEGER := 0;
BEGIN
	INSERT INTO AULA (TL_AULA, DS_AULA, ID_CURSO, LINK_AULA, DT_CADASTRO)
        VALUES (P_TL_AULA, P_DS_AULA, P_ID_CURSO, P_LINK_AULA, CURRENT_TIMESTAMP);
        RETURNING ID_AULA INTO ID_NOVO;
	RETURN ID_NOVO;
END;
$BODY$
LANGUAGE plpgsql VOLATILE;

---------------------------------------------------------------------------------------------------------------------------------------------------------------






